package it.unical.mat.andlv.test;

/**
 * Created by Dave on 02/04/2015.
 */
public class RandomFact {
    public static final String fact1000="detected_activity(1,\"ON_BICYCLE\",27).\n" +
            "detected_activity(2,\"ON_FOOT\",20).\n" +
            "detected_activity(3,\"ON_BICYCLE\",87).\n" +
            "detected_activity(4,\"IN_VEHICLE\",48).\n" +
            "detected_activity(5,\"IN_VEHICLE\",85).\n" +
            "detected_activity(6,\"ON_FOOT\",45).\n" +
            "detected_activity(7,\"ON_FOOT\",28).\n" +
            "detected_activity(8,\"IN_VEHICLE\",66).\n" +
            "detected_activity(9,\"ON_BICYCLE\",78).\n" +
            "detected_activity(10,\"IN_VEHICLE\",37).\n" +
            "detected_activity(11,\"IN_VEHICLE\",62).\n" +
            "detected_activity(12,\"ON_FOOT\",30).\n" +
            "detected_activity(13,\"ON_BICYCLE\",87).\n" +
            "detected_activity(14,\"ON_FOOT\",31).\n" +
            "detected_activity(15,\"ON_FOOT\",45).\n" +
            "detected_activity(16,\"ON_FOOT\",40).\n" +
            "detected_activity(17,\"ON_BICYCLE\",55).\n" +
            "detected_activity(18,\"IN_VEHICLE\",66).\n" +
            "detected_activity(19,\"ON_BICYCLE\",13).\n" +
            "detected_activity(20,\"ON_FOOT\",62).\n" +
            "detected_activity(21,\"IN_VEHICLE\",100).\n" +
            "detected_activity(22,\"ON_FOOT\",12).\n" +
            "detected_activity(23,\"IN_VEHICLE\",43).\n" +
            "detected_activity(24,\"ON_BICYCLE\",99).\n" +
            "detected_activity(25,\"ON_FOOT\",3).\n" +
            "detected_activity(26,\"ON_BICYCLE\",10).\n" +
            "detected_activity(27,\"ON_FOOT\",77).\n" +
            "detected_activity(28,\"ON_FOOT\",7).\n" +
            "detected_activity(29,\"ON_BICYCLE\",93).\n" +
            "detected_activity(30,\"ON_BICYCLE\",77).\n" +
            "detected_activity(31,\"ON_FOOT\",71).\n" +
            "detected_activity(32,\"IN_VEHICLE\",71).\n" +
            "detected_activity(33,\"ON_BICYCLE\",66).\n" +
            "detected_activity(34,\"IN_VEHICLE\",72).\n" +
            "detected_activity(35,\"ON_BICYCLE\",76).\n" +
            "detected_activity(36,\"ON_BICYCLE\",5).\n" +
            "detected_activity(37,\"ON_BICYCLE\",46).\n" +
            "detected_activity(38,\"ON_FOOT\",9).\n" +
            "detected_activity(39,\"ON_BICYCLE\",36).\n" +
            "detected_activity(40,\"IN_VEHICLE\",2).\n" +
            "detected_activity(41,\"ON_BICYCLE\",62).\n" +
            "detected_activity(42,\"ON_FOOT\",73).\n" +
            "detected_activity(43,\"ON_BICYCLE\",7).\n" +
            "detected_activity(44,\"ON_BICYCLE\",47).\n" +
            "detected_activity(45,\"IN_VEHICLE\",14).\n" +
            "detected_activity(46,\"IN_VEHICLE\",37).\n" +
            "detected_activity(47,\"ON_FOOT\",28).\n" +
            "detected_activity(48,\"ON_BICYCLE\",100).\n" +
            "detected_activity(49,\"ON_FOOT\",69).\n" +
            "detected_activity(50,\"ON_FOOT\",85).\n" +
            "detected_activity(51,\"IN_VEHICLE\",23).\n" +
            "detected_activity(52,\"ON_BICYCLE\",96).\n" +
            "detected_activity(53,\"IN_VEHICLE\",44).\n" +
            "detected_activity(54,\"ON_FOOT\",21).\n" +
            "detected_activity(55,\"ON_BICYCLE\",43).\n" +
            "detected_activity(56,\"ON_FOOT\",19).\n" +
            "detected_activity(57,\"ON_BICYCLE\",94).\n" +
            "detected_activity(58,\"ON_FOOT\",14).\n" +
            "detected_activity(59,\"ON_BICYCLE\",14).\n" +
            "detected_activity(60,\"ON_FOOT\",33).\n" +
            "detected_activity(61,\"ON_FOOT\",48).\n" +
            "detected_activity(62,\"IN_VEHICLE\",94).\n" +
            "detected_activity(63,\"ON_FOOT\",89).\n" +
            "detected_activity(64,\"IN_VEHICLE\",21).\n" +
            "detected_activity(65,\"IN_VEHICLE\",100).\n" +
            "detected_activity(66,\"IN_VEHICLE\",68).\n" +
            "detected_activity(67,\"ON_BICYCLE\",71).\n" +
            "detected_activity(68,\"IN_VEHICLE\",46).\n" +
            "detected_activity(69,\"IN_VEHICLE\",17).\n" +
            "detected_activity(70,\"ON_FOOT\",58).\n" +
            "detected_activity(71,\"ON_FOOT\",90).\n" +
            "detected_activity(72,\"ON_FOOT\",99).\n" +
            "detected_activity(73,\"IN_VEHICLE\",47).\n" +
            "detected_activity(74,\"ON_BICYCLE\",30).\n" +
            "detected_activity(75,\"ON_BICYCLE\",54).\n" +
            "detected_activity(76,\"IN_VEHICLE\",81).\n" +
            "detected_activity(77,\"IN_VEHICLE\",38).\n" +
            "detected_activity(78,\"ON_FOOT\",6).\n" +
            "detected_activity(79,\"ON_FOOT\",12).\n" +
            "detected_activity(80,\"IN_VEHICLE\",29).\n" +
            "detected_activity(81,\"ON_FOOT\",31).\n" +
            "detected_activity(82,\"IN_VEHICLE\",100).\n" +
            "detected_activity(83,\"IN_VEHICLE\",26).\n" +
            "detected_activity(84,\"ON_BICYCLE\",50).\n" +
            "detected_activity(85,\"ON_BICYCLE\",7).\n" +
            "detected_activity(86,\"ON_BICYCLE\",2).\n" +
            "detected_activity(87,\"IN_VEHICLE\",83).\n" +
            "detected_activity(88,\"IN_VEHICLE\",47).\n" +
            "detected_activity(89,\"IN_VEHICLE\",40).\n" +
            "detected_activity(90,\"ON_BICYCLE\",76).\n" +
            "detected_activity(91,\"ON_BICYCLE\",0).\n" +
            "detected_activity(92,\"ON_BICYCLE\",52).\n" +
            "detected_activity(93,\"ON_BICYCLE\",98).\n" +
            "detected_activity(94,\"ON_FOOT\",41).\n" +
            "detected_activity(95,\"ON_FOOT\",80).\n" +
            "detected_activity(96,\"ON_BICYCLE\",3).\n" +
            "detected_activity(97,\"ON_FOOT\",79).\n" +
            "detected_activity(98,\"ON_FOOT\",1).\n" +
            "detected_activity(99,\"IN_VEHICLE\",22).\n" +
            "detected_activity(100,\"ON_BICYCLE\",43).\n" +
            "detected_activity(101,\"IN_VEHICLE\",99).\n" +
            "detected_activity(102,\"ON_BICYCLE\",6).\n" +
            "detected_activity(103,\"ON_FOOT\",2).\n" +
            "detected_activity(104,\"ON_BICYCLE\",69).\n" +
            "detected_activity(105,\"ON_FOOT\",15).\n" +
            "detected_activity(106,\"IN_VEHICLE\",82).\n" +
            "detected_activity(107,\"IN_VEHICLE\",92).\n" +
            "detected_activity(108,\"ON_BICYCLE\",77).\n" +
            "detected_activity(109,\"IN_VEHICLE\",40).\n" +
            "detected_activity(110,\"ON_FOOT\",48).\n" +
            "detected_activity(111,\"ON_FOOT\",63).\n" +
            "detected_activity(112,\"IN_VEHICLE\",16).\n" +
            "detected_activity(113,\"IN_VEHICLE\",42).\n" +
            "detected_activity(114,\"IN_VEHICLE\",53).\n" +
            "detected_activity(115,\"IN_VEHICLE\",84).\n" +
            "detected_activity(116,\"ON_BICYCLE\",96).\n" +
            "detected_activity(117,\"ON_FOOT\",83).\n" +
            "detected_activity(118,\"IN_VEHICLE\",79).\n" +
            "detected_activity(119,\"ON_BICYCLE\",54).\n" +
            "detected_activity(120,\"IN_VEHICLE\",53).\n" +
            "detected_activity(121,\"ON_FOOT\",76).\n" +
            "detected_activity(122,\"IN_VEHICLE\",69).\n" +
            "detected_activity(123,\"ON_BICYCLE\",35).\n" +
            "detected_activity(124,\"ON_FOOT\",38).\n" +
            "detected_activity(125,\"ON_FOOT\",0).\n" +
            "detected_activity(126,\"IN_VEHICLE\",61).\n" +
            "detected_activity(127,\"IN_VEHICLE\",75).\n" +
            "detected_activity(128,\"IN_VEHICLE\",19).\n" +
            "detected_activity(129,\"ON_BICYCLE\",29).\n" +
            "detected_activity(130,\"ON_FOOT\",22).\n" +
            "detected_activity(131,\"IN_VEHICLE\",93).\n" +
            "detected_activity(132,\"IN_VEHICLE\",99).\n" +
            "detected_activity(133,\"ON_BICYCLE\",35).\n" +
            "detected_activity(134,\"ON_BICYCLE\",11).\n" +
            "detected_activity(135,\"IN_VEHICLE\",31).\n" +
            "detected_activity(136,\"IN_VEHICLE\",61).\n" +
            "detected_activity(137,\"ON_BICYCLE\",22).\n" +
            "detected_activity(138,\"ON_FOOT\",19).\n" +
            "detected_activity(139,\"ON_BICYCLE\",46).\n" +
            "detected_activity(140,\"ON_FOOT\",62).\n" +
            "detected_activity(141,\"ON_BICYCLE\",69).\n" +
            "detected_activity(142,\"IN_VEHICLE\",69).\n" +
            "detected_activity(143,\"IN_VEHICLE\",46).\n" +
            "detected_activity(144,\"IN_VEHICLE\",40).\n" +
            "detected_activity(145,\"IN_VEHICLE\",28).\n" +
            "detected_activity(146,\"ON_BICYCLE\",86).\n" +
            "detected_activity(147,\"ON_FOOT\",100).\n" +
            "detected_activity(148,\"IN_VEHICLE\",79).\n" +
            "detected_activity(149,\"ON_BICYCLE\",36).\n" +
            "detected_activity(150,\"ON_FOOT\",97).\n" +
            "detected_activity(151,\"ON_FOOT\",26).\n" +
            "detected_activity(152,\"ON_FOOT\",56).\n" +
            "detected_activity(153,\"IN_VEHICLE\",60).\n" +
            "detected_activity(154,\"ON_FOOT\",53).\n" +
            "detected_activity(155,\"ON_BICYCLE\",42).\n" +
            "detected_activity(156,\"IN_VEHICLE\",75).\n" +
            "detected_activity(157,\"ON_BICYCLE\",7).\n" +
            "detected_activity(158,\"ON_BICYCLE\",97).\n" +
            "detected_activity(159,\"IN_VEHICLE\",92).\n" +
            "detected_activity(160,\"ON_FOOT\",63).\n" +
            "detected_activity(161,\"ON_FOOT\",56).\n" +
            "detected_activity(162,\"IN_VEHICLE\",72).\n" +
            "detected_activity(163,\"ON_FOOT\",24).\n" +
            "detected_activity(164,\"IN_VEHICLE\",0).\n" +
            "detected_activity(165,\"ON_FOOT\",86).\n" +
            "detected_activity(166,\"ON_FOOT\",88).\n" +
            "detected_activity(167,\"ON_BICYCLE\",55).\n" +
            "detected_activity(168,\"ON_BICYCLE\",38).\n" +
            "detected_activity(169,\"IN_VEHICLE\",11).\n" +
            "detected_activity(170,\"ON_BICYCLE\",48).\n" +
            "detected_activity(171,\"IN_VEHICLE\",61).\n" +
            "detected_activity(172,\"IN_VEHICLE\",62).\n" +
            "detected_activity(173,\"ON_BICYCLE\",96).\n" +
            "detected_activity(174,\"ON_FOOT\",51).\n" +
            "detected_activity(175,\"ON_FOOT\",2).\n" +
            "detected_activity(176,\"ON_FOOT\",22).\n" +
            "detected_activity(177,\"ON_FOOT\",58).\n" +
            "detected_activity(178,\"ON_BICYCLE\",83).\n" +
            "detected_activity(179,\"ON_BICYCLE\",2).\n" +
            "detected_activity(180,\"ON_BICYCLE\",99).\n" +
            "detected_activity(181,\"IN_VEHICLE\",84).\n" +
            "detected_activity(182,\"ON_BICYCLE\",49).\n" +
            "detected_activity(183,\"ON_BICYCLE\",33).\n" +
            "detected_activity(184,\"ON_FOOT\",20).\n" +
            "detected_activity(185,\"IN_VEHICLE\",2).\n" +
            "detected_activity(186,\"ON_FOOT\",80).\n" +
            "detected_activity(187,\"ON_FOOT\",54).\n" +
            "detected_activity(188,\"ON_FOOT\",91).\n" +
            "detected_activity(189,\"ON_FOOT\",38).\n" +
            "detected_activity(190,\"IN_VEHICLE\",86).\n" +
            "detected_activity(191,\"ON_FOOT\",24).\n" +
            "detected_activity(192,\"ON_FOOT\",74).\n" +
            "detected_activity(193,\"IN_VEHICLE\",79).\n" +
            "detected_activity(194,\"ON_FOOT\",46).\n" +
            "detected_activity(195,\"ON_FOOT\",32).\n" +
            "detected_activity(196,\"ON_FOOT\",6).\n" +
            "detected_activity(197,\"ON_FOOT\",97).\n" +
            "detected_activity(198,\"ON_FOOT\",45).\n" +
            "detected_activity(199,\"ON_FOOT\",65).\n" +
            "detected_activity(200,\"IN_VEHICLE\",1).\n" +
            "detected_activity(201,\"ON_BICYCLE\",49).\n" +
            "detected_activity(202,\"ON_BICYCLE\",99).\n" +
            "detected_activity(203,\"ON_FOOT\",91).\n" +
            "detected_activity(204,\"ON_BICYCLE\",43).\n" +
            "detected_activity(205,\"IN_VEHICLE\",11).\n" +
            "detected_activity(206,\"ON_BICYCLE\",36).\n" +
            "detected_activity(207,\"ON_BICYCLE\",59).\n" +
            "detected_activity(208,\"ON_FOOT\",90).\n" +
            "detected_activity(209,\"ON_FOOT\",87).\n" +
            "detected_activity(210,\"ON_FOOT\",46).\n" +
            "detected_activity(211,\"ON_FOOT\",53).\n" +
            "detected_activity(212,\"ON_FOOT\",3).\n" +
            "detected_activity(213,\"ON_BICYCLE\",84).\n" +
            "detected_activity(214,\"ON_FOOT\",27).\n" +
            "detected_activity(215,\"IN_VEHICLE\",83).\n" +
            "detected_activity(216,\"IN_VEHICLE\",89).\n" +
            "detected_activity(217,\"ON_BICYCLE\",16).\n" +
            "detected_activity(218,\"IN_VEHICLE\",21).\n" +
            "detected_activity(219,\"IN_VEHICLE\",32).\n" +
            "detected_activity(220,\"ON_BICYCLE\",9).\n" +
            "detected_activity(221,\"ON_BICYCLE\",82).\n" +
            "detected_activity(222,\"ON_FOOT\",59).\n" +
            "detected_activity(223,\"IN_VEHICLE\",61).\n" +
            "detected_activity(224,\"ON_BICYCLE\",19).\n" +
            "detected_activity(225,\"ON_FOOT\",81).\n" +
            "detected_activity(226,\"ON_FOOT\",78).\n" +
            "detected_activity(227,\"ON_BICYCLE\",29).\n" +
            "detected_activity(228,\"ON_FOOT\",61).\n" +
            "detected_activity(229,\"ON_BICYCLE\",17).\n" +
            "detected_activity(230,\"IN_VEHICLE\",51).\n" +
            "detected_activity(231,\"ON_FOOT\",95).\n" +
            "detected_activity(232,\"ON_BICYCLE\",20).\n" +
            "detected_activity(233,\"ON_FOOT\",86).\n" +
            "detected_activity(234,\"ON_BICYCLE\",71).\n" +
            "detected_activity(235,\"IN_VEHICLE\",32).\n" +
            "detected_activity(236,\"ON_BICYCLE\",84).\n" +
            "detected_activity(237,\"IN_VEHICLE\",40).\n" +
            "detected_activity(238,\"IN_VEHICLE\",51).\n" +
            "detected_activity(239,\"IN_VEHICLE\",51).\n" +
            "detected_activity(240,\"ON_FOOT\",79).\n" +
            "detected_activity(241,\"ON_FOOT\",26).\n" +
            "detected_activity(242,\"ON_BICYCLE\",91).\n" +
            "detected_activity(243,\"ON_BICYCLE\",73).\n" +
            "detected_activity(244,\"IN_VEHICLE\",15).\n" +
            "detected_activity(245,\"IN_VEHICLE\",60).\n" +
            "detected_activity(246,\"ON_FOOT\",96).\n" +
            "detected_activity(247,\"IN_VEHICLE\",94).\n" +
            "detected_activity(248,\"IN_VEHICLE\",27).\n" +
            "detected_activity(249,\"ON_FOOT\",88).\n" +
            "detected_activity(250,\"ON_FOOT\",23).\n" +
            "detected_activity(251,\"ON_BICYCLE\",98).\n" +
            "detected_activity(252,\"IN_VEHICLE\",32).\n" +
            "detected_activity(253,\"IN_VEHICLE\",28).\n" +
            "detected_activity(254,\"ON_FOOT\",74).\n" +
            "detected_activity(255,\"ON_BICYCLE\",24).\n" +
            "detected_activity(256,\"IN_VEHICLE\",5).\n" +
            "detected_activity(257,\"ON_FOOT\",96).\n" +
            "detected_activity(258,\"ON_BICYCLE\",47).\n" +
            "detected_activity(259,\"ON_FOOT\",63).\n" +
            "detected_activity(260,\"ON_FOOT\",26).\n" +
            "detected_activity(261,\"IN_VEHICLE\",33).\n" +
            "detected_activity(262,\"ON_FOOT\",15).\n" +
            "detected_activity(263,\"ON_BICYCLE\",63).\n" +
            "detected_activity(264,\"ON_BICYCLE\",2).\n" +
            "detected_activity(265,\"ON_BICYCLE\",45).\n" +
            "detected_activity(266,\"IN_VEHICLE\",0).\n" +
            "detected_activity(267,\"ON_FOOT\",74).\n" +
            "detected_activity(268,\"ON_BICYCLE\",60).\n" +
            "detected_activity(269,\"IN_VEHICLE\",76).\n" +
            "detected_activity(270,\"ON_FOOT\",49).\n" +
            "detected_activity(271,\"ON_FOOT\",80).\n" +
            "detected_activity(272,\"ON_BICYCLE\",47).\n" +
            "detected_activity(273,\"ON_FOOT\",31).\n" +
            "detected_activity(274,\"ON_BICYCLE\",69).\n" +
            "detected_activity(275,\"IN_VEHICLE\",6).\n" +
            "detected_activity(276,\"IN_VEHICLE\",76).\n" +
            "detected_activity(277,\"ON_FOOT\",47).\n" +
            "detected_activity(278,\"IN_VEHICLE\",91).\n" +
            "detected_activity(279,\"ON_BICYCLE\",53).\n" +
            "detected_activity(280,\"IN_VEHICLE\",6).\n" +
            "detected_activity(281,\"ON_BICYCLE\",79).\n" +
            "detected_activity(282,\"IN_VEHICLE\",81).\n" +
            "detected_activity(283,\"ON_FOOT\",98).\n" +
            "detected_activity(284,\"ON_FOOT\",42).\n" +
            "detected_activity(285,\"ON_BICYCLE\",19).\n" +
            "detected_activity(286,\"ON_BICYCLE\",71).\n" +
            "detected_activity(287,\"ON_FOOT\",38).\n" +
            "detected_activity(288,\"IN_VEHICLE\",6).\n" +
            "detected_activity(289,\"ON_FOOT\",9).\n" +
            "detected_activity(290,\"ON_FOOT\",12).\n" +
            "detected_activity(291,\"IN_VEHICLE\",93).\n" +
            "detected_activity(292,\"ON_FOOT\",45).\n" +
            "detected_activity(293,\"ON_FOOT\",20).\n" +
            "detected_activity(294,\"ON_BICYCLE\",8).\n" +
            "detected_activity(295,\"ON_FOOT\",49).\n" +
            "detected_activity(296,\"ON_BICYCLE\",82).\n" +
            "detected_activity(297,\"ON_BICYCLE\",32).\n" +
            "detected_activity(298,\"IN_VEHICLE\",45).\n" +
            "detected_activity(299,\"IN_VEHICLE\",70).\n" +
            "detected_activity(300,\"IN_VEHICLE\",68).\n" +
            "detected_activity(301,\"ON_FOOT\",49).\n" +
            "detected_activity(302,\"IN_VEHICLE\",79).\n" +
            "detected_activity(303,\"ON_FOOT\",90).\n" +
            "detected_activity(304,\"IN_VEHICLE\",25).\n" +
            "detected_activity(305,\"ON_BICYCLE\",27).\n" +
            "detected_activity(306,\"IN_VEHICLE\",14).\n" +
            "detected_activity(307,\"IN_VEHICLE\",99).\n" +
            "detected_activity(308,\"ON_FOOT\",25).\n" +
            "detected_activity(309,\"ON_BICYCLE\",60).\n" +
            "detected_activity(310,\"IN_VEHICLE\",47).\n" +
            "detected_activity(311,\"ON_BICYCLE\",5).\n" +
            "detected_activity(312,\"ON_FOOT\",2).\n" +
            "detected_activity(313,\"IN_VEHICLE\",50).\n" +
            "detected_activity(314,\"IN_VEHICLE\",44).\n" +
            "detected_activity(315,\"IN_VEHICLE\",95).\n" +
            "detected_activity(316,\"ON_FOOT\",34).\n" +
            "detected_activity(317,\"ON_FOOT\",24).\n" +
            "detected_activity(318,\"ON_FOOT\",56).\n" +
            "detected_activity(319,\"IN_VEHICLE\",20).\n" +
            "detected_activity(320,\"ON_FOOT\",26).\n" +
            "detected_activity(321,\"ON_FOOT\",93).\n" +
            "detected_activity(322,\"ON_FOOT\",75).\n" +
            "detected_activity(323,\"ON_BICYCLE\",79).\n" +
            "detected_activity(324,\"ON_FOOT\",25).\n" +
            "detected_activity(325,\"ON_FOOT\",33).\n" +
            "detected_activity(326,\"ON_BICYCLE\",93).\n" +
            "detected_activity(327,\"ON_BICYCLE\",88).\n" +
            "detected_activity(328,\"ON_FOOT\",31).\n" +
            "detected_activity(329,\"ON_BICYCLE\",75).\n" +
            "detected_activity(330,\"ON_BICYCLE\",4).\n" +
            "detected_activity(331,\"IN_VEHICLE\",43).\n" +
            "detected_activity(332,\"ON_BICYCLE\",63).\n" +
            "detected_activity(333,\"ON_FOOT\",19).\n" +
            "detected_activity(334,\"IN_VEHICLE\",80).\n" +
            "detected_activity(335,\"ON_BICYCLE\",75).\n" +
            "detected_activity(336,\"ON_BICYCLE\",86).\n" +
            "detected_activity(337,\"IN_VEHICLE\",44).\n" +
            "detected_activity(338,\"ON_FOOT\",14).\n" +
            "detected_activity(339,\"IN_VEHICLE\",5).\n" +
            "detected_activity(340,\"IN_VEHICLE\",97).\n" +
            "detected_activity(341,\"ON_FOOT\",95).\n" +
            "detected_activity(342,\"ON_FOOT\",49).\n" +
            "detected_activity(343,\"ON_FOOT\",60).\n" +
            "detected_activity(344,\"ON_BICYCLE\",19).\n" +
            "detected_activity(345,\"ON_FOOT\",9).\n" +
            "detected_activity(346,\"IN_VEHICLE\",48).\n" +
            "detected_activity(347,\"ON_FOOT\",80).\n" +
            "detected_activity(348,\"ON_FOOT\",67).\n" +
            "detected_activity(349,\"ON_FOOT\",43).\n" +
            "detected_activity(350,\"IN_VEHICLE\",4).\n" +
            "detected_activity(351,\"ON_FOOT\",98).\n" +
            "detected_activity(352,\"ON_FOOT\",77).\n" +
            "detected_activity(353,\"IN_VEHICLE\",56).\n" +
            "detected_activity(354,\"IN_VEHICLE\",60).\n" +
            "detected_activity(355,\"IN_VEHICLE\",3).\n" +
            "detected_activity(356,\"ON_FOOT\",56).\n" +
            "detected_activity(357,\"ON_FOOT\",11).\n" +
            "detected_activity(358,\"IN_VEHICLE\",90).\n" +
            "detected_activity(359,\"IN_VEHICLE\",95).\n" +
            "detected_activity(360,\"IN_VEHICLE\",3).\n" +
            "detected_activity(361,\"IN_VEHICLE\",84).\n" +
            "detected_activity(362,\"ON_FOOT\",59).\n" +
            "detected_activity(363,\"ON_FOOT\",12).\n" +
            "detected_activity(364,\"ON_BICYCLE\",30).\n" +
            "detected_activity(365,\"IN_VEHICLE\",85).\n" +
            "detected_activity(366,\"ON_BICYCLE\",98).\n" +
            "detected_activity(367,\"ON_FOOT\",6).\n" +
            "detected_activity(368,\"ON_FOOT\",34).\n" +
            "detected_activity(369,\"ON_BICYCLE\",90).\n" +
            "detected_activity(370,\"IN_VEHICLE\",9).\n" +
            "detected_activity(371,\"IN_VEHICLE\",25).\n" +
            "detected_activity(372,\"ON_FOOT\",38).\n" +
            "detected_activity(373,\"IN_VEHICLE\",43).\n" +
            "detected_activity(374,\"IN_VEHICLE\",1).\n" +
            "detected_activity(375,\"IN_VEHICLE\",25).\n" +
            "detected_activity(376,\"IN_VEHICLE\",49).\n" +
            "detected_activity(377,\"ON_FOOT\",90).\n" +
            "detected_activity(378,\"ON_BICYCLE\",61).\n" +
            "detected_activity(379,\"ON_FOOT\",9).\n" +
            "detected_activity(380,\"IN_VEHICLE\",48).\n" +
            "detected_activity(381,\"ON_FOOT\",35).\n" +
            "detected_activity(382,\"ON_BICYCLE\",97).\n" +
            "detected_activity(383,\"ON_BICYCLE\",47).\n" +
            "detected_activity(384,\"ON_FOOT\",92).\n" +
            "detected_activity(385,\"ON_BICYCLE\",27).\n" +
            "detected_activity(386,\"IN_VEHICLE\",27).\n" +
            "detected_activity(387,\"ON_BICYCLE\",20).\n" +
            "detected_activity(388,\"ON_BICYCLE\",36).\n" +
            "detected_activity(389,\"ON_BICYCLE\",15).\n" +
            "detected_activity(390,\"ON_FOOT\",67).\n" +
            "detected_activity(391,\"ON_FOOT\",14).\n" +
            "detected_activity(392,\"ON_FOOT\",94).\n" +
            "detected_activity(393,\"ON_FOOT\",35).\n" +
            "detected_activity(394,\"IN_VEHICLE\",37).\n" +
            "detected_activity(395,\"ON_FOOT\",39).\n" +
            "detected_activity(396,\"ON_BICYCLE\",74).\n" +
            "detected_activity(397,\"ON_BICYCLE\",29).\n" +
            "detected_activity(398,\"IN_VEHICLE\",32).\n" +
            "detected_activity(399,\"ON_BICYCLE\",85).\n" +
            "detected_activity(400,\"IN_VEHICLE\",37).\n" +
            "detected_activity(401,\"ON_BICYCLE\",43).\n" +
            "detected_activity(402,\"IN_VEHICLE\",13).\n" +
            "detected_activity(403,\"ON_FOOT\",55).\n" +
            "detected_activity(404,\"ON_BICYCLE\",68).\n" +
            "detected_activity(405,\"ON_FOOT\",46).\n" +
            "detected_activity(406,\"IN_VEHICLE\",36).\n" +
            "detected_activity(407,\"ON_FOOT\",74).\n" +
            "detected_activity(408,\"IN_VEHICLE\",38).\n" +
            "detected_activity(409,\"IN_VEHICLE\",44).\n" +
            "detected_activity(410,\"IN_VEHICLE\",66).\n" +
            "detected_activity(411,\"IN_VEHICLE\",71).\n" +
            "detected_activity(412,\"ON_BICYCLE\",33).\n" +
            "detected_activity(413,\"ON_FOOT\",71).\n" +
            "detected_activity(414,\"IN_VEHICLE\",68).\n" +
            "detected_activity(415,\"IN_VEHICLE\",65).\n" +
            "detected_activity(416,\"IN_VEHICLE\",53).\n" +
            "detected_activity(417,\"IN_VEHICLE\",63).\n" +
            "detected_activity(418,\"ON_FOOT\",5).\n" +
            "detected_activity(419,\"IN_VEHICLE\",16).\n" +
            "detected_activity(420,\"IN_VEHICLE\",40).\n" +
            "detected_activity(421,\"ON_BICYCLE\",81).\n" +
            "detected_activity(422,\"ON_FOOT\",47).\n" +
            "detected_activity(423,\"ON_BICYCLE\",92).\n" +
            "detected_activity(424,\"ON_BICYCLE\",30).\n" +
            "detected_activity(425,\"ON_FOOT\",89).\n" +
            "detected_activity(426,\"ON_BICYCLE\",2).\n" +
            "detected_activity(427,\"ON_FOOT\",4).\n" +
            "detected_activity(428,\"IN_VEHICLE\",37).\n" +
            "detected_activity(429,\"ON_BICYCLE\",80).\n" +
            "detected_activity(430,\"ON_BICYCLE\",2).\n" +
            "detected_activity(431,\"IN_VEHICLE\",22).\n" +
            "detected_activity(432,\"ON_FOOT\",62).\n" +
            "detected_activity(433,\"ON_BICYCLE\",68).\n" +
            "detected_activity(434,\"IN_VEHICLE\",59).\n" +
            "detected_activity(435,\"ON_BICYCLE\",71).\n" +
            "detected_activity(436,\"ON_FOOT\",39).\n" +
            "detected_activity(437,\"IN_VEHICLE\",60).\n" +
            "detected_activity(438,\"IN_VEHICLE\",28).\n" +
            "detected_activity(439,\"ON_FOOT\",20).\n" +
            "detected_activity(440,\"ON_BICYCLE\",100).\n" +
            "detected_activity(441,\"ON_FOOT\",72).\n" +
            "detected_activity(442,\"ON_BICYCLE\",65).\n" +
            "detected_activity(443,\"ON_BICYCLE\",66).\n" +
            "detected_activity(444,\"IN_VEHICLE\",62).\n" +
            "detected_activity(445,\"ON_FOOT\",9).\n" +
            "detected_activity(446,\"IN_VEHICLE\",95).\n" +
            "detected_activity(447,\"ON_BICYCLE\",55).\n" +
            "detected_activity(448,\"IN_VEHICLE\",56).\n" +
            "detected_activity(449,\"IN_VEHICLE\",75).\n" +
            "detected_activity(450,\"ON_BICYCLE\",52).\n" +
            "detected_activity(451,\"IN_VEHICLE\",10).\n" +
            "detected_activity(452,\"ON_FOOT\",5).\n" +
            "detected_activity(453,\"ON_BICYCLE\",7).\n" +
            "detected_activity(454,\"ON_BICYCLE\",50).\n" +
            "detected_activity(455,\"ON_BICYCLE\",67).\n" +
            "detected_activity(456,\"ON_FOOT\",89).\n" +
            "detected_activity(457,\"ON_FOOT\",23).\n" +
            "detected_activity(458,\"IN_VEHICLE\",75).\n" +
            "detected_activity(459,\"ON_BICYCLE\",15).\n" +
            "detected_activity(460,\"ON_BICYCLE\",40).\n" +
            "detected_activity(461,\"IN_VEHICLE\",0).\n" +
            "detected_activity(462,\"ON_FOOT\",45).\n" +
            "detected_activity(463,\"IN_VEHICLE\",44).\n" +
            "detected_activity(464,\"IN_VEHICLE\",47).\n" +
            "detected_activity(465,\"ON_BICYCLE\",63).\n" +
            "detected_activity(466,\"ON_FOOT\",74).\n" +
            "detected_activity(467,\"ON_BICYCLE\",41).\n" +
            "detected_activity(468,\"ON_FOOT\",47).\n" +
            "detected_activity(469,\"ON_FOOT\",53).\n" +
            "detected_activity(470,\"ON_BICYCLE\",57).\n" +
            "detected_activity(471,\"ON_FOOT\",40).\n" +
            "detected_activity(472,\"ON_FOOT\",31).\n" +
            "detected_activity(473,\"IN_VEHICLE\",67).\n" +
            "detected_activity(474,\"IN_VEHICLE\",3).\n" +
            "detected_activity(475,\"IN_VEHICLE\",34).\n" +
            "detected_activity(476,\"IN_VEHICLE\",5).\n" +
            "detected_activity(477,\"ON_FOOT\",0).\n" +
            "detected_activity(478,\"ON_FOOT\",1).\n" +
            "detected_activity(479,\"ON_BICYCLE\",46).\n" +
            "detected_activity(480,\"IN_VEHICLE\",85).\n" +
            "detected_activity(481,\"ON_FOOT\",86).\n" +
            "detected_activity(482,\"ON_BICYCLE\",36).\n" +
            "detected_activity(483,\"IN_VEHICLE\",73).\n" +
            "detected_activity(484,\"IN_VEHICLE\",37).\n" +
            "detected_activity(485,\"IN_VEHICLE\",65).\n" +
            "detected_activity(486,\"ON_BICYCLE\",54).\n" +
            "detected_activity(487,\"ON_BICYCLE\",5).\n" +
            "detected_activity(488,\"ON_BICYCLE\",28).\n" +
            "detected_activity(489,\"ON_FOOT\",94).\n" +
            "detected_activity(490,\"ON_BICYCLE\",67).\n" +
            "detected_activity(491,\"IN_VEHICLE\",23).\n" +
            "detected_activity(492,\"IN_VEHICLE\",52).\n" +
            "detected_activity(493,\"ON_BICYCLE\",10).\n" +
            "detected_activity(494,\"ON_FOOT\",27).\n" +
            "detected_activity(495,\"ON_BICYCLE\",20).\n" +
            "detected_activity(496,\"IN_VEHICLE\",0).\n" +
            "detected_activity(497,\"ON_BICYCLE\",22).\n" +
            "detected_activity(498,\"ON_FOOT\",73).\n" +
            "detected_activity(499,\"IN_VEHICLE\",50).\n" +
            "detected_activity(500,\"IN_VEHICLE\",46).\n" +
            "detected_activity(501,\"ON_BICYCLE\",29).\n" +
            "detected_activity(502,\"IN_VEHICLE\",71).\n" +
            "detected_activity(503,\"ON_FOOT\",99).\n" +
            "detected_activity(504,\"IN_VEHICLE\",71).\n" +
            "detected_activity(505,\"IN_VEHICLE\",97).\n" +
            "detected_activity(506,\"IN_VEHICLE\",27).\n" +
            "detected_activity(507,\"IN_VEHICLE\",79).\n" +
            "detected_activity(508,\"IN_VEHICLE\",52).\n" +
            "detected_activity(509,\"ON_BICYCLE\",11).\n" +
            "detected_activity(510,\"IN_VEHICLE\",87).\n" +
            "detected_activity(511,\"IN_VEHICLE\",36).\n" +
            "detected_activity(512,\"IN_VEHICLE\",25).\n" +
            "detected_activity(513,\"ON_BICYCLE\",11).\n" +
            "detected_activity(514,\"IN_VEHICLE\",51).\n" +
            "detected_activity(515,\"ON_BICYCLE\",72).\n" +
            "detected_activity(516,\"ON_BICYCLE\",52).\n" +
            "detected_activity(517,\"ON_BICYCLE\",27).\n" +
            "detected_activity(518,\"ON_FOOT\",81).\n" +
            "detected_activity(519,\"IN_VEHICLE\",39).\n" +
            "detected_activity(520,\"ON_FOOT\",60).\n" +
            "detected_activity(521,\"ON_BICYCLE\",23).\n" +
            "detected_activity(522,\"ON_FOOT\",49).\n" +
            "detected_activity(523,\"ON_FOOT\",77).\n" +
            "detected_activity(524,\"ON_BICYCLE\",82).\n" +
            "detected_activity(525,\"ON_FOOT\",15).\n" +
            "detected_activity(526,\"ON_FOOT\",96).\n" +
            "detected_activity(527,\"IN_VEHICLE\",16).\n" +
            "detected_activity(528,\"ON_FOOT\",20).\n" +
            "detected_activity(529,\"ON_FOOT\",33).\n" +
            "detected_activity(530,\"ON_BICYCLE\",83).\n" +
            "detected_activity(531,\"ON_BICYCLE\",64).\n" +
            "detected_activity(532,\"IN_VEHICLE\",0).\n" +
            "detected_activity(533,\"ON_BICYCLE\",72).\n" +
            "detected_activity(534,\"IN_VEHICLE\",95).\n" +
            "detected_activity(535,\"ON_FOOT\",12).\n" +
            "detected_activity(536,\"IN_VEHICLE\",73).\n" +
            "detected_activity(537,\"IN_VEHICLE\",93).\n" +
            "detected_activity(538,\"ON_BICYCLE\",58).\n" +
            "detected_activity(539,\"IN_VEHICLE\",39).\n" +
            "detected_activity(540,\"ON_FOOT\",9).\n" +
            "detected_activity(541,\"IN_VEHICLE\",83).\n" +
            "detected_activity(542,\"IN_VEHICLE\",87).\n" +
            "detected_activity(543,\"IN_VEHICLE\",56).\n" +
            "detected_activity(544,\"ON_BICYCLE\",97).\n" +
            "detected_activity(545,\"ON_FOOT\",66).\n" +
            "detected_activity(546,\"ON_FOOT\",44).\n" +
            "detected_activity(547,\"ON_FOOT\",38).\n" +
            "detected_activity(548,\"ON_FOOT\",33).\n" +
            "detected_activity(549,\"ON_FOOT\",31).\n" +
            "detected_activity(550,\"ON_BICYCLE\",12).\n" +
            "detected_activity(551,\"ON_FOOT\",42).\n" +
            "detected_activity(552,\"IN_VEHICLE\",32).\n" +
            "detected_activity(553,\"ON_FOOT\",13).\n" +
            "detected_activity(554,\"ON_FOOT\",47).\n" +
            "detected_activity(555,\"IN_VEHICLE\",3).\n" +
            "detected_activity(556,\"ON_BICYCLE\",94).\n" +
            "detected_activity(557,\"ON_BICYCLE\",80).\n" +
            "detected_activity(558,\"ON_BICYCLE\",43).\n" +
            "detected_activity(559,\"IN_VEHICLE\",76).\n" +
            "detected_activity(560,\"ON_BICYCLE\",37).\n" +
            "detected_activity(561,\"IN_VEHICLE\",93).\n" +
            "detected_activity(562,\"ON_FOOT\",90).\n" +
            "detected_activity(563,\"ON_BICYCLE\",4).\n" +
            "detected_activity(564,\"ON_BICYCLE\",60).\n" +
            "detected_activity(565,\"ON_FOOT\",16).\n" +
            "detected_activity(566,\"IN_VEHICLE\",51).\n" +
            "detected_activity(567,\"ON_BICYCLE\",36).\n" +
            "detected_activity(568,\"ON_BICYCLE\",10).\n" +
            "detected_activity(569,\"IN_VEHICLE\",83).\n" +
            "detected_activity(570,\"ON_BICYCLE\",99).\n" +
            "detected_activity(571,\"IN_VEHICLE\",77).\n" +
            "detected_activity(572,\"ON_BICYCLE\",36).\n" +
            "detected_activity(573,\"ON_FOOT\",0).\n" +
            "detected_activity(574,\"ON_FOOT\",49).\n" +
            "detected_activity(575,\"IN_VEHICLE\",60).\n" +
            "detected_activity(576,\"ON_FOOT\",8).\n" +
            "detected_activity(577,\"ON_FOOT\",90).\n" +
            "detected_activity(578,\"ON_BICYCLE\",82).\n" +
            "detected_activity(579,\"IN_VEHICLE\",65).\n" +
            "detected_activity(580,\"IN_VEHICLE\",18).\n" +
            "detected_activity(581,\"ON_BICYCLE\",59).\n" +
            "detected_activity(582,\"ON_FOOT\",25).\n" +
            "detected_activity(583,\"IN_VEHICLE\",27).\n" +
            "detected_activity(584,\"ON_BICYCLE\",48).\n" +
            "detected_activity(585,\"IN_VEHICLE\",81).\n" +
            "detected_activity(586,\"ON_FOOT\",48).\n" +
            "detected_activity(587,\"ON_BICYCLE\",0).\n" +
            "detected_activity(588,\"ON_FOOT\",52).\n" +
            "detected_activity(589,\"IN_VEHICLE\",15).\n" +
            "detected_activity(590,\"ON_FOOT\",2).\n" +
            "detected_activity(591,\"ON_BICYCLE\",19).\n" +
            "detected_activity(592,\"ON_BICYCLE\",84).\n" +
            "detected_activity(593,\"ON_BICYCLE\",52).\n" +
            "detected_activity(594,\"ON_FOOT\",9).\n" +
            "detected_activity(595,\"IN_VEHICLE\",63).\n" +
            "detected_activity(596,\"ON_FOOT\",56).\n" +
            "detected_activity(597,\"IN_VEHICLE\",46).\n" +
            "detected_activity(598,\"IN_VEHICLE\",11).\n" +
            "detected_activity(599,\"ON_FOOT\",74).\n" +
            "detected_activity(600,\"ON_BICYCLE\",1).\n" +
            "detected_activity(601,\"IN_VEHICLE\",38).\n" +
            "detected_activity(602,\"IN_VEHICLE\",60).\n" +
            "detected_activity(603,\"IN_VEHICLE\",87).\n" +
            "detected_activity(604,\"ON_BICYCLE\",93).\n" +
            "detected_activity(605,\"ON_FOOT\",2).\n" +
            "detected_activity(606,\"ON_FOOT\",47).\n" +
            "detected_activity(607,\"IN_VEHICLE\",44).\n" +
            "detected_activity(608,\"ON_FOOT\",45).\n" +
            "detected_activity(609,\"ON_FOOT\",9).\n" +
            "detected_activity(610,\"ON_FOOT\",29).\n" +
            "detected_activity(611,\"ON_FOOT\",22).\n" +
            "detected_activity(612,\"ON_FOOT\",11).\n" +
            "detected_activity(613,\"IN_VEHICLE\",49).\n" +
            "detected_activity(614,\"IN_VEHICLE\",55).\n" +
            "detected_activity(615,\"ON_BICYCLE\",70).\n" +
            "detected_activity(616,\"ON_FOOT\",2).\n" +
            "detected_activity(617,\"ON_FOOT\",17).\n" +
            "detected_activity(618,\"ON_FOOT\",49).\n" +
            "detected_activity(619,\"ON_BICYCLE\",71).\n" +
            "detected_activity(620,\"ON_BICYCLE\",86).\n" +
            "detected_activity(621,\"ON_BICYCLE\",94).\n" +
            "detected_activity(622,\"ON_BICYCLE\",67).\n" +
            "detected_activity(623,\"IN_VEHICLE\",80).\n" +
            "detected_activity(624,\"ON_FOOT\",98).\n" +
            "detected_activity(625,\"IN_VEHICLE\",82).\n" +
            "detected_activity(626,\"ON_FOOT\",86).\n" +
            "detected_activity(627,\"IN_VEHICLE\",29).\n" +
            "detected_activity(628,\"IN_VEHICLE\",23).\n" +
            "detected_activity(629,\"ON_FOOT\",12).\n" +
            "detected_activity(630,\"ON_BICYCLE\",71).\n" +
            "detected_activity(631,\"ON_BICYCLE\",8).\n" +
            "detected_activity(632,\"IN_VEHICLE\",58).\n" +
            "detected_activity(633,\"ON_FOOT\",46).\n" +
            "detected_activity(634,\"IN_VEHICLE\",14).\n" +
            "detected_activity(635,\"ON_FOOT\",38).\n" +
            "detected_activity(636,\"ON_BICYCLE\",26).\n" +
            "detected_activity(637,\"ON_FOOT\",5).\n" +
            "detected_activity(638,\"IN_VEHICLE\",3).\n" +
            "detected_activity(639,\"IN_VEHICLE\",90).\n" +
            "detected_activity(640,\"ON_FOOT\",72).\n" +
            "detected_activity(641,\"IN_VEHICLE\",16).\n" +
            "detected_activity(642,\"ON_BICYCLE\",62).\n" +
            "detected_activity(643,\"IN_VEHICLE\",8).\n" +
            "detected_activity(644,\"ON_BICYCLE\",20).\n" +
            "detected_activity(645,\"IN_VEHICLE\",29).\n" +
            "detected_activity(646,\"IN_VEHICLE\",83).\n" +
            "detected_activity(647,\"IN_VEHICLE\",54).\n" +
            "detected_activity(648,\"ON_FOOT\",47).\n" +
            "detected_activity(649,\"ON_FOOT\",80).\n" +
            "detected_activity(650,\"ON_BICYCLE\",19).\n" +
            "detected_activity(651,\"ON_FOOT\",66).\n" +
            "detected_activity(652,\"ON_FOOT\",85).\n" +
            "detected_activity(653,\"IN_VEHICLE\",88).\n" +
            "detected_activity(654,\"ON_FOOT\",30).\n" +
            "detected_activity(655,\"ON_BICYCLE\",51).\n" +
            "detected_activity(656,\"IN_VEHICLE\",33).\n" +
            "detected_activity(657,\"ON_FOOT\",69).\n" +
            "detected_activity(658,\"ON_BICYCLE\",9).\n" +
            "detected_activity(659,\"ON_BICYCLE\",48).\n" +
            "detected_activity(660,\"IN_VEHICLE\",54).\n" +
            "detected_activity(661,\"IN_VEHICLE\",83).\n" +
            "detected_activity(662,\"ON_FOOT\",50).\n" +
            "detected_activity(663,\"ON_BICYCLE\",70).\n" +
            "detected_activity(664,\"IN_VEHICLE\",68).\n" +
            "detected_activity(665,\"ON_BICYCLE\",9).\n" +
            "detected_activity(666,\"ON_FOOT\",76).\n" +
            "detected_activity(667,\"ON_FOOT\",36).\n" +
            "detected_activity(668,\"ON_FOOT\",72).\n" +
            "detected_activity(669,\"IN_VEHICLE\",56).\n" +
            "detected_activity(670,\"ON_BICYCLE\",52).\n" +
            "detected_activity(671,\"IN_VEHICLE\",26).\n" +
            "detected_activity(672,\"ON_BICYCLE\",71).\n" +
            "detected_activity(673,\"ON_BICYCLE\",71).\n" +
            "detected_activity(674,\"IN_VEHICLE\",1).\n" +
            "detected_activity(675,\"ON_BICYCLE\",12).\n" +
            "detected_activity(676,\"ON_FOOT\",12).\n" +
            "detected_activity(677,\"IN_VEHICLE\",74).\n" +
            "detected_activity(678,\"IN_VEHICLE\",47).\n" +
            "detected_activity(679,\"ON_BICYCLE\",49).\n" +
            "detected_activity(680,\"ON_BICYCLE\",80).\n" +
            "detected_activity(681,\"ON_FOOT\",0).\n" +
            "detected_activity(682,\"ON_FOOT\",91).\n" +
            "detected_activity(683,\"ON_BICYCLE\",67).\n" +
            "detected_activity(684,\"IN_VEHICLE\",12).\n" +
            "detected_activity(685,\"ON_FOOT\",38).\n" +
            "detected_activity(686,\"IN_VEHICLE\",61).\n" +
            "detected_activity(687,\"IN_VEHICLE\",72).\n" +
            "detected_activity(688,\"IN_VEHICLE\",10).\n" +
            "detected_activity(689,\"ON_BICYCLE\",31).\n" +
            "detected_activity(690,\"ON_FOOT\",71).\n" +
            "detected_activity(691,\"ON_BICYCLE\",3).\n" +
            "detected_activity(692,\"ON_FOOT\",66).\n" +
            "detected_activity(693,\"ON_FOOT\",10).\n" +
            "detected_activity(694,\"ON_FOOT\",18).\n" +
            "detected_activity(695,\"ON_BICYCLE\",13).\n" +
            "detected_activity(696,\"ON_FOOT\",92).\n" +
            "detected_activity(697,\"ON_FOOT\",74).\n" +
            "detected_activity(698,\"IN_VEHICLE\",100).\n" +
            "detected_activity(699,\"IN_VEHICLE\",12).\n" +
            "detected_activity(700,\"ON_BICYCLE\",83).\n" +
            "detected_activity(701,\"ON_FOOT\",8).\n" +
            "detected_activity(702,\"ON_FOOT\",16).\n" +
            "detected_activity(703,\"IN_VEHICLE\",24).\n" +
            "detected_activity(704,\"IN_VEHICLE\",94).\n" +
            "detected_activity(705,\"ON_BICYCLE\",33).\n" +
            "detected_activity(706,\"ON_FOOT\",72).\n" +
            "detected_activity(707,\"IN_VEHICLE\",13).\n" +
            "detected_activity(708,\"ON_FOOT\",5).\n" +
            "detected_activity(709,\"IN_VEHICLE\",90).\n" +
            "detected_activity(710,\"ON_FOOT\",86).\n" +
            "detected_activity(711,\"IN_VEHICLE\",2).\n" +
            "detected_activity(712,\"ON_FOOT\",56).\n" +
            "detected_activity(713,\"ON_FOOT\",23).\n" +
            "detected_activity(714,\"ON_BICYCLE\",74).\n" +
            "detected_activity(715,\"IN_VEHICLE\",83).\n" +
            "detected_activity(716,\"ON_FOOT\",51).\n" +
            "detected_activity(717,\"IN_VEHICLE\",38).\n" +
            "detected_activity(718,\"ON_FOOT\",90).\n" +
            "detected_activity(719,\"ON_BICYCLE\",23).\n" +
            "detected_activity(720,\"ON_FOOT\",86).\n" +
            "detected_activity(721,\"IN_VEHICLE\",62).\n" +
            "detected_activity(722,\"IN_VEHICLE\",26).\n" +
            "detected_activity(723,\"IN_VEHICLE\",24).\n" +
            "detected_activity(724,\"IN_VEHICLE\",5).\n" +
            "detected_activity(725,\"IN_VEHICLE\",32).\n" +
            "detected_activity(726,\"ON_FOOT\",43).\n" +
            "detected_activity(727,\"ON_FOOT\",34).\n" +
            "detected_activity(728,\"ON_FOOT\",93).\n" +
            "detected_activity(729,\"ON_BICYCLE\",74).\n" +
            "detected_activity(730,\"ON_BICYCLE\",12).\n" +
            "detected_activity(731,\"ON_BICYCLE\",35).\n" +
            "detected_activity(732,\"ON_BICYCLE\",87).\n" +
            "detected_activity(733,\"ON_FOOT\",28).\n" +
            "detected_activity(734,\"IN_VEHICLE\",19).\n" +
            "detected_activity(735,\"ON_FOOT\",10).\n" +
            "detected_activity(736,\"IN_VEHICLE\",51).\n" +
            "detected_activity(737,\"ON_FOOT\",23).\n" +
            "detected_activity(738,\"ON_BICYCLE\",88).\n" +
            "detected_activity(739,\"ON_BICYCLE\",98).\n" +
            "detected_activity(740,\"ON_FOOT\",79).\n" +
            "detected_activity(741,\"ON_FOOT\",21).\n" +
            "detected_activity(742,\"ON_BICYCLE\",92).\n" +
            "detected_activity(743,\"ON_FOOT\",65).\n" +
            "detected_activity(744,\"IN_VEHICLE\",32).\n" +
            "detected_activity(745,\"IN_VEHICLE\",67).\n" +
            "detected_activity(746,\"ON_FOOT\",1).\n" +
            "detected_activity(747,\"IN_VEHICLE\",79).\n" +
            "detected_activity(748,\"ON_BICYCLE\",69).\n" +
            "detected_activity(749,\"IN_VEHICLE\",57).\n" +
            "detected_activity(750,\"IN_VEHICLE\",36).\n" +
            "detected_activity(751,\"IN_VEHICLE\",64).\n" +
            "detected_activity(752,\"ON_FOOT\",49).\n" +
            "detected_activity(753,\"IN_VEHICLE\",99).\n" +
            "detected_activity(754,\"ON_FOOT\",98).\n" +
            "detected_activity(755,\"ON_FOOT\",16).\n" +
            "detected_activity(756,\"IN_VEHICLE\",65).\n" +
            "detected_activity(757,\"IN_VEHICLE\",87).\n" +
            "detected_activity(758,\"IN_VEHICLE\",67).\n" +
            "detected_activity(759,\"IN_VEHICLE\",2).\n" +
            "detected_activity(760,\"ON_BICYCLE\",86).\n" +
            "detected_activity(761,\"ON_BICYCLE\",6).\n" +
            "detected_activity(762,\"IN_VEHICLE\",67).\n" +
            "detected_activity(763,\"ON_FOOT\",52).\n" +
            "detected_activity(764,\"ON_FOOT\",65).\n" +
            "detected_activity(765,\"ON_FOOT\",18).\n" +
            "detected_activity(766,\"IN_VEHICLE\",7).\n" +
            "detected_activity(767,\"ON_BICYCLE\",13).\n" +
            "detected_activity(768,\"IN_VEHICLE\",14).\n" +
            "detected_activity(769,\"ON_FOOT\",94).\n" +
            "detected_activity(770,\"ON_FOOT\",59).\n" +
            "detected_activity(771,\"IN_VEHICLE\",6).\n" +
            "detected_activity(772,\"IN_VEHICLE\",4).\n" +
            "detected_activity(773,\"ON_FOOT\",90).\n" +
            "detected_activity(774,\"ON_FOOT\",6).\n" +
            "detected_activity(775,\"ON_FOOT\",38).\n" +
            "detected_activity(776,\"ON_FOOT\",28).\n" +
            "detected_activity(777,\"ON_FOOT\",11).\n" +
            "detected_activity(778,\"ON_BICYCLE\",90).\n" +
            "detected_activity(779,\"ON_BICYCLE\",22).\n" +
            "detected_activity(780,\"ON_BICYCLE\",11).\n" +
            "detected_activity(781,\"ON_BICYCLE\",71).\n" +
            "detected_activity(782,\"IN_VEHICLE\",43).\n" +
            "detected_activity(783,\"IN_VEHICLE\",83).\n" +
            "detected_activity(784,\"ON_BICYCLE\",40).\n" +
            "detected_activity(785,\"IN_VEHICLE\",14).\n" +
            "detected_activity(786,\"ON_FOOT\",95).\n" +
            "detected_activity(787,\"ON_FOOT\",20).\n" +
            "detected_activity(788,\"IN_VEHICLE\",39).\n" +
            "detected_activity(789,\"IN_VEHICLE\",64).\n" +
            "detected_activity(790,\"ON_BICYCLE\",7).\n" +
            "detected_activity(791,\"ON_FOOT\",20).\n" +
            "detected_activity(792,\"IN_VEHICLE\",16).\n" +
            "detected_activity(793,\"ON_FOOT\",36).\n" +
            "detected_activity(794,\"ON_BICYCLE\",17).\n" +
            "detected_activity(795,\"IN_VEHICLE\",48).\n" +
            "detected_activity(796,\"ON_FOOT\",57).\n" +
            "detected_activity(797,\"ON_BICYCLE\",72).\n" +
            "detected_activity(798,\"ON_FOOT\",17).\n" +
            "detected_activity(799,\"ON_FOOT\",24).\n" +
            "detected_activity(800,\"ON_BICYCLE\",53).\n" +
            "detected_activity(801,\"ON_BICYCLE\",42).\n" +
            "detected_activity(802,\"IN_VEHICLE\",30).\n" +
            "detected_activity(803,\"ON_BICYCLE\",0).\n" +
            "detected_activity(804,\"ON_FOOT\",13).\n" +
            "detected_activity(805,\"ON_BICYCLE\",47).\n" +
            "detected_activity(806,\"ON_FOOT\",29).\n" +
            "detected_activity(807,\"ON_BICYCLE\",47).\n" +
            "detected_activity(808,\"IN_VEHICLE\",14).\n" +
            "detected_activity(809,\"ON_FOOT\",7).\n" +
            "detected_activity(810,\"ON_BICYCLE\",32).\n" +
            "detected_activity(811,\"ON_FOOT\",64).\n" +
            "detected_activity(812,\"ON_FOOT\",18).\n" +
            "detected_activity(813,\"ON_BICYCLE\",32).\n" +
            "detected_activity(814,\"ON_FOOT\",56).\n" +
            "detected_activity(815,\"IN_VEHICLE\",74).\n" +
            "detected_activity(816,\"IN_VEHICLE\",96).\n" +
            "detected_activity(817,\"ON_FOOT\",37).\n" +
            "detected_activity(818,\"ON_FOOT\",61).\n" +
            "detected_activity(819,\"ON_FOOT\",95).\n" +
            "detected_activity(820,\"IN_VEHICLE\",93).\n" +
            "detected_activity(821,\"ON_FOOT\",74).\n" +
            "detected_activity(822,\"ON_BICYCLE\",81).\n" +
            "detected_activity(823,\"ON_BICYCLE\",9).\n" +
            "detected_activity(824,\"ON_FOOT\",61).\n" +
            "detected_activity(825,\"ON_BICYCLE\",13).\n" +
            "detected_activity(826,\"IN_VEHICLE\",24).\n" +
            "detected_activity(827,\"ON_FOOT\",38).\n" +
            "detected_activity(828,\"IN_VEHICLE\",89).\n" +
            "detected_activity(829,\"ON_BICYCLE\",50).\n" +
            "detected_activity(830,\"ON_BICYCLE\",47).\n" +
            "detected_activity(831,\"IN_VEHICLE\",94).\n" +
            "detected_activity(832,\"ON_BICYCLE\",90).\n" +
            "detected_activity(833,\"ON_BICYCLE\",38).\n" +
            "detected_activity(834,\"ON_BICYCLE\",38).\n" +
            "detected_activity(835,\"ON_BICYCLE\",61).\n" +
            "detected_activity(836,\"IN_VEHICLE\",80).\n" +
            "detected_activity(837,\"ON_FOOT\",61).\n" +
            "detected_activity(838,\"ON_BICYCLE\",57).\n" +
            "detected_activity(839,\"ON_FOOT\",40).\n" +
            "detected_activity(840,\"IN_VEHICLE\",30).\n" +
            "detected_activity(841,\"ON_BICYCLE\",17).\n" +
            "detected_activity(842,\"ON_FOOT\",14).\n" +
            "detected_activity(843,\"ON_BICYCLE\",38).\n" +
            "detected_activity(844,\"IN_VEHICLE\",67).\n" +
            "detected_activity(845,\"ON_BICYCLE\",63).\n" +
            "detected_activity(846,\"IN_VEHICLE\",7).\n" +
            "detected_activity(847,\"IN_VEHICLE\",46).\n" +
            "detected_activity(848,\"IN_VEHICLE\",20).\n" +
            "detected_activity(849,\"ON_FOOT\",93).\n" +
            "detected_activity(850,\"ON_FOOT\",45).\n" +
            "detected_activity(851,\"ON_FOOT\",21).\n" +
            "detected_activity(852,\"ON_BICYCLE\",61).\n" +
            "detected_activity(853,\"ON_BICYCLE\",46).\n" +
            "detected_activity(854,\"IN_VEHICLE\",55).\n" +
            "detected_activity(855,\"ON_BICYCLE\",23).\n" +
            "detected_activity(856,\"ON_BICYCLE\",53).\n" +
            "detected_activity(857,\"ON_FOOT\",25).\n" +
            "detected_activity(858,\"ON_FOOT\",83).\n" +
            "detected_activity(859,\"ON_BICYCLE\",80).\n" +
            "detected_activity(860,\"ON_FOOT\",31).\n" +
            "detected_activity(861,\"IN_VEHICLE\",85).\n" +
            "detected_activity(862,\"ON_FOOT\",71).\n" +
            "detected_activity(863,\"ON_FOOT\",45).\n" +
            "detected_activity(864,\"ON_FOOT\",87).\n" +
            "detected_activity(865,\"ON_FOOT\",81).\n" +
            "detected_activity(866,\"ON_BICYCLE\",95).\n" +
            "detected_activity(867,\"ON_BICYCLE\",3).\n" +
            "detected_activity(868,\"IN_VEHICLE\",32).\n" +
            "detected_activity(869,\"ON_BICYCLE\",25).\n" +
            "detected_activity(870,\"ON_BICYCLE\",44).\n" +
            "detected_activity(871,\"ON_FOOT\",7).\n" +
            "detected_activity(872,\"ON_BICYCLE\",19).\n" +
            "detected_activity(873,\"ON_BICYCLE\",73).\n" +
            "detected_activity(874,\"IN_VEHICLE\",53).\n" +
            "detected_activity(875,\"IN_VEHICLE\",85).\n" +
            "detected_activity(876,\"ON_FOOT\",40).\n" +
            "detected_activity(877,\"ON_FOOT\",62).\n" +
            "detected_activity(878,\"ON_BICYCLE\",42).\n" +
            "detected_activity(879,\"ON_FOOT\",48).\n" +
            "detected_activity(880,\"ON_FOOT\",84).\n" +
            "detected_activity(881,\"ON_BICYCLE\",72).\n" +
            "detected_activity(882,\"IN_VEHICLE\",1).\n" +
            "detected_activity(883,\"IN_VEHICLE\",36).\n" +
            "detected_activity(884,\"IN_VEHICLE\",73).\n" +
            "detected_activity(885,\"ON_FOOT\",45).\n" +
            "detected_activity(886,\"IN_VEHICLE\",19).\n" +
            "detected_activity(887,\"ON_FOOT\",78).\n" +
            "detected_activity(888,\"IN_VEHICLE\",38).\n" +
            "detected_activity(889,\"ON_BICYCLE\",72).\n" +
            "detected_activity(890,\"ON_FOOT\",76).\n" +
            "detected_activity(891,\"ON_FOOT\",10).\n" +
            "detected_activity(892,\"IN_VEHICLE\",76).\n" +
            "detected_activity(893,\"ON_BICYCLE\",5).\n" +
            "detected_activity(894,\"IN_VEHICLE\",64).\n" +
            "detected_activity(895,\"IN_VEHICLE\",16).\n" +
            "detected_activity(896,\"ON_FOOT\",49).\n" +
            "detected_activity(897,\"IN_VEHICLE\",77).\n" +
            "detected_activity(898,\"ON_BICYCLE\",98).\n" +
            "detected_activity(899,\"ON_BICYCLE\",25).\n" +
            "detected_activity(900,\"ON_BICYCLE\",88).\n" +
            "detected_activity(901,\"IN_VEHICLE\",90).\n" +
            "detected_activity(902,\"ON_BICYCLE\",94).\n" +
            "detected_activity(903,\"IN_VEHICLE\",31).\n" +
            "detected_activity(904,\"ON_FOOT\",94).\n" +
            "detected_activity(905,\"ON_FOOT\",67).\n" +
            "detected_activity(906,\"ON_BICYCLE\",66).\n" +
            "detected_activity(907,\"ON_FOOT\",3).\n" +
            "detected_activity(908,\"ON_BICYCLE\",15).\n" +
            "detected_activity(909,\"ON_BICYCLE\",51).\n" +
            "detected_activity(910,\"IN_VEHICLE\",56).\n" +
            "detected_activity(911,\"IN_VEHICLE\",23).\n" +
            "detected_activity(912,\"ON_FOOT\",37).\n" +
            "detected_activity(913,\"IN_VEHICLE\",26).\n" +
            "detected_activity(914,\"IN_VEHICLE\",6).\n" +
            "detected_activity(915,\"ON_BICYCLE\",90).\n" +
            "detected_activity(916,\"ON_FOOT\",0).\n" +
            "detected_activity(917,\"IN_VEHICLE\",22).\n" +
            "detected_activity(918,\"ON_BICYCLE\",91).\n" +
            "detected_activity(919,\"ON_FOOT\",14).\n" +
            "detected_activity(920,\"ON_FOOT\",46).\n" +
            "detected_activity(921,\"IN_VEHICLE\",63).\n" +
            "detected_activity(922,\"ON_FOOT\",51).\n" +
            "detected_activity(923,\"IN_VEHICLE\",12).\n" +
            "detected_activity(924,\"ON_BICYCLE\",43).\n" +
            "detected_activity(925,\"IN_VEHICLE\",91).\n" +
            "detected_activity(926,\"ON_FOOT\",62).\n" +
            "detected_activity(927,\"ON_BICYCLE\",27).\n" +
            "detected_activity(928,\"ON_FOOT\",61).\n" +
            "detected_activity(929,\"IN_VEHICLE\",49).\n" +
            "detected_activity(930,\"ON_BICYCLE\",66).\n" +
            "detected_activity(931,\"IN_VEHICLE\",76).\n" +
            "detected_activity(932,\"IN_VEHICLE\",15).\n" +
            "detected_activity(933,\"ON_FOOT\",24).\n" +
            "detected_activity(934,\"ON_FOOT\",67).\n" +
            "detected_activity(935,\"ON_BICYCLE\",60).\n" +
            "detected_activity(936,\"IN_VEHICLE\",27).\n" +
            "detected_activity(937,\"ON_BICYCLE\",59).\n" +
            "detected_activity(938,\"ON_BICYCLE\",59).\n" +
            "detected_activity(939,\"ON_BICYCLE\",29).\n" +
            "detected_activity(940,\"IN_VEHICLE\",87).\n" +
            "detected_activity(941,\"IN_VEHICLE\",35).\n" +
            "detected_activity(942,\"ON_BICYCLE\",71).\n" +
            "detected_activity(943,\"ON_BICYCLE\",92).\n" +
            "detected_activity(944,\"IN_VEHICLE\",60).\n" +
            "detected_activity(945,\"ON_BICYCLE\",82).\n" +
            "detected_activity(946,\"ON_FOOT\",11).\n" +
            "detected_activity(947,\"ON_FOOT\",28).\n" +
            "detected_activity(948,\"IN_VEHICLE\",31).\n" +
            "detected_activity(949,\"ON_FOOT\",86).\n" +
            "detected_activity(950,\"ON_FOOT\",35).\n" +
            "detected_activity(951,\"IN_VEHICLE\",87).\n" +
            "detected_activity(952,\"ON_BICYCLE\",95).\n" +
            "detected_activity(953,\"IN_VEHICLE\",45).\n" +
            "detected_activity(954,\"ON_BICYCLE\",25).\n" +
            "detected_activity(955,\"ON_FOOT\",97).\n" +
            "detected_activity(956,\"ON_BICYCLE\",8).\n" +
            "detected_activity(957,\"ON_BICYCLE\",47).\n" +
            "detected_activity(958,\"IN_VEHICLE\",44).\n" +
            "detected_activity(959,\"ON_BICYCLE\",72).\n" +
            "detected_activity(960,\"ON_BICYCLE\",41).\n" +
            "detected_activity(961,\"IN_VEHICLE\",66).\n" +
            "detected_activity(962,\"ON_FOOT\",100).\n" +
            "detected_activity(963,\"ON_FOOT\",49).\n" +
            "detected_activity(964,\"IN_VEHICLE\",22).\n" +
            "detected_activity(965,\"IN_VEHICLE\",98).\n" +
            "detected_activity(966,\"IN_VEHICLE\",22).\n" +
            "detected_activity(967,\"ON_FOOT\",2).\n" +
            "detected_activity(968,\"ON_BICYCLE\",65).\n" +
            "detected_activity(969,\"IN_VEHICLE\",16).\n" +
            "detected_activity(970,\"ON_BICYCLE\",42).\n" +
            "detected_activity(971,\"ON_FOOT\",32).\n" +
            "detected_activity(972,\"ON_FOOT\",3).\n" +
            "detected_activity(973,\"ON_FOOT\",100).\n" +
            "detected_activity(974,\"ON_FOOT\",22).\n" +
            "detected_activity(975,\"ON_BICYCLE\",48).\n" +
            "detected_activity(976,\"IN_VEHICLE\",34).\n" +
            "detected_activity(977,\"ON_BICYCLE\",86).\n" +
            "detected_activity(978,\"IN_VEHICLE\",8).\n" +
            "detected_activity(979,\"ON_BICYCLE\",0).\n" +
            "detected_activity(980,\"ON_FOOT\",69).\n" +
            "detected_activity(981,\"ON_BICYCLE\",93).\n" +
            "detected_activity(982,\"IN_VEHICLE\",19).\n" +
            "detected_activity(983,\"ON_BICYCLE\",66).\n" +
            "detected_activity(984,\"IN_VEHICLE\",16).\n" +
            "detected_activity(985,\"ON_BICYCLE\",48).\n" +
            "detected_activity(986,\"IN_VEHICLE\",14).\n" +
            "detected_activity(987,\"IN_VEHICLE\",23).\n" +
            "detected_activity(988,\"ON_FOOT\",61).\n" +
            "detected_activity(989,\"IN_VEHICLE\",12).\n" +
            "detected_activity(990,\"IN_VEHICLE\",34).\n" +
            "detected_activity(991,\"ON_FOOT\",30).\n" +
            "detected_activity(992,\"ON_FOOT\",29).\n" +
            "detected_activity(993,\"ON_FOOT\",94).\n" +
            "detected_activity(994,\"IN_VEHICLE\",61).\n" +
            "detected_activity(995,\"ON_FOOT\",4).\n" +
            "detected_activity(996,\"ON_BICYCLE\",63).\n" +
            "detected_activity(997,\"ON_BICYCLE\",89).\n" +
            "detected_activity(998,\"IN_VEHICLE\",78).\n" +
            "detected_activity(999,\"ON_BICYCLE\",53).\n" +
            "detected_activity(1000,\"ON_FOOT\",65).\n";
}
